# Dimensions

## Customer Dimension

In [ ]:
# Install faker

!pip install faker pyarrow pandas numpy -q

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.1/2.1 MB 27.9 MB/s eta 0:00:00

In [ ]:
# Libraries and random seed
import random
import numpy as np
import pandas as pd

from faker import Faker
from google.colab import files

fake = Faker()

Faker.seed(42)
random.seed(42)
np.random.seed(42)

In [ ]:
# Customer configuration

NUMBER_OF_CUSTOMERS = 50000
RANDOM_SEED = 42
OUTPUT_FORMAT = "Both"      # CSV, Parquet, Both
SOURCE_SYSTEM = "CRM"
START_CUSTOMER_ID = 100001

In [ ]:
# Master data generator
customer_types = [
    "Enterprise",
    "SMB",
    "Government",
    "Education"
]

customer_type_weights = [
    35,
    45,
    10,
    10
]

industries = [
    "Manufacturing",
    "Retail",
    "Financial Services",
    "Healthcare",
    "Technology",
    "Energy",
    "Telecommunications",
    "Public Sector",
    "Education",
    "Logistics"
]

countries = {
    "United States": ["Seattle","Dallas","Chicago","New York"],
    "Canada": ["Toronto","Vancouver","Calgary"],
    "United Kingdom": ["London","Manchester","Birmingham"],
    "Germany": ["Munich","Berlin","Frankfurt"],
    "France": ["Paris","Lyon"],
    "Netherlands": ["Amsterdam","Rotterdam"],
    "India": ["Bengaluru","Mumbai","Hyderabad","Pune"],
    "Singapore": ["Singapore"],
    "Australia": ["Sydney","Melbourne"],
    "Japan": ["Tokyo","Osaka"],
    "United Arab Emirates": ["Dubai","Abu Dhabi"]
}

territory = {
    "United States":"AMER",
    "Canada":"AMER",
    "United Kingdom":"EMEA",
    "Germany":"EMEA",
    "France":"EMEA",
    "Netherlands":"EMEA",
    "United Arab Emirates":"EMEA",
    "India":"APAC",
    "Singapore":"APAC",
    "Australia":"APAC",
    "Japan":"APAC"
}

In [ ]:
# Company name generator
prefix = [
    "Northwind",
    "BluePeak",
    "Vertex",
    "Summit",
    "Global",
    "Sterling",
    "Evergreen",
    "Pacific",
    "Apex",
    "Horizon",
    "Prime",
    "Quantum",
    "Pioneer",
    "Atlas",
    "Nimbus",
    "Crystal",
    "Velocity",
    "Fusion"
]

suffix = [
    "Manufacturing",
    "Retail",
    "Logistics",
    "Industrial",
    "Engineering",
    "Healthcare",
    "Financial",
    "Energy",
    "Solutions",
    "Technologies",
    "Systems",
    "Holdings",
    "Distribution",
    "Consulting",
    "Partners"
]

legal = {
    "United States":"Inc.",
    "Canada":"Ltd.",
    "United Kingdom":"Ltd",
    "Germany":"GmbH",
    "France":"SAS",
    "Netherlands":"B.V.",
    "India":"Pvt Ltd",
    "Singapore":"Pte Ltd",
    "Australia":"Pty Ltd",
    "Japan":"KK",
    "United Arab Emirates":"LLC"
}

In [ ]:
# Generate data
rows = []

for customer_id in range(
        START_CUSTOMER_ID,
        START_CUSTOMER_ID + NUMBER_OF_CUSTOMERS):

    country = random.choice(list(countries.keys()))

    city = random.choice(countries[country])

    company = (
        random.choice(prefix)
        + " "
        + random.choice(suffix)
        + " "
        + legal[country]
    )

    created = fake.date_between(
        start_date="-5y",
        end_date="-1y"
    )

    modified = fake.date_between(
        start_date=created,
        end_date="today"
    )

    rows.append({

        "CustomerID": customer_id,

        "CustomerCode": f"CUST-{customer_id}",

        "CustomerName": company,

        "CustomerType": random.choices(
            customer_types,
            weights=customer_type_weights
        )[0],

        "Industry": random.choice(industries),

        "SalesTerritory": territory[country],

        "Country": country,

        "StateProvince": fake.state(),

        "City": city,

        "PostalCode": fake.postcode(),

        "EmailAddress":
            "info@"
            + company.lower()
                     .replace(" ","")
                     .replace(".","")
                     .replace("&","")
            + ".com",

        "PhoneNumber": fake.phone_number(),

        "Status":
            "Active"
            if random.random() < 0.92
            else "Inactive",

        "CreatedDate": created,

        "ModifiedDate": modified,

        "SourceSystem": "CRM"

    })

customers = pd.DataFrame(rows)

customers.head()

,CustomerID,CustomerCode,CustomerName,CustomerType,Industry,SalesTerritory,Country,StateProvince,City,PostalCode,EmailAddress,PhoneNumber,Status,CreatedDate,ModifiedDate,SourceSystem
0,100001,CUST-100001,Northwind Holdings LLC,Enterprise,Healthcare,EMEA,United Arab Emirates,Louisiana,Dubai,32599,info@northwindholdingsllc.com,321.581.9600,Active,2024-02-25,2024-03-18,CRM
1,100002,CUST-100002,Fusion Retail Ltd.,SMB,Manufacturing,AMER,Canada,Oklahoma,Calgary,26563,info@fusionretailltd.com,001-486-537-9402x654,Active,2022-07-10,2024-12-21,CRM
2,100003,CUST-100003,Velocity Technologies GmbH,Enterprise,Healthcare,EMEA,Germany,Colorado,Munich,50298,info@velocitytechnologiesgmbh.com,855-394-0781,Active,2025-06-03,2025-10-25,CRM
3,100004,CUST-100004,Pacific Energy Pty Ltd,SMB,Manufacturing,APAC,Australia,South Carolina,Melbourne,47901,info@pacificenergyptyltd.com,001-831-603-4131,Active,2023-10-20,2026-02-12,CRM
4,100005,CUST-100005,Atlas Healthcare Ltd,Enterprise,Healthcare,EMEA,United Kingdom,Hawaii,Birmingham,49021,info@atlashealthcareltd.com,(534)719-2832x764,Inactive,2023-05-29,2026-01-24,CRM

In [ ]:
# Validate data
print(customers.shape)

customers.info()

customers.describe(include="all")

(50000, 16)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 16 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   CustomerID      50000 non-null  int64
 1   CustomerCode    50000 non-null  object
 2   CustomerName    50000 non-null  object
 3   CustomerType    50000 non-null  object
 4   Industry        50000 non-null  object
 5   SalesTerritory  50000 non-null  object
 6   Country         50000 non-null  object
 7   StateProvince   50000 non-null  object
 8   City            50000 non-null  object
 9   PostalCode      50000 non-null  object
 10  EmailAddress    50000 non-null  object
 11  PhoneNumber     50000 non-null  object
 12  Status          50000 non-null  object
 13  CreatedDate     50000 non-null  object
 14  ModifiedDate    50000 non-null  object
 15  SourceSystem    50000 non-null  object
dtypes: int64(1), object(15)
memory usage: 6.1+ MB

,CustomerID,CustomerCode,CustomerName,CustomerType,Industry,SalesTerritory,Country,StateProvince,City,PostalCode,EmailAddress,PhoneNumber,Status,CreatedDate,ModifiedDate,SourceSystem
count,50000.000000,50000,50000,50000,50000,50000,50000,50000,50000,50000,50000,50000,50000,50000,50000,50000
unique,NaN,50000,2970,4,10,3,11,50,28,39320,2700,50000,2,1461,1780,1
top,NaN,CUST-149984,Evergreen Holdings Ltd.,SMB,Energy,EMEA,Japan,New Jersey,Singapore,44613,info@evergreenholdingsltd.com,001-428-254-3801x80900,Active,2024-08-23,2026-07-30,CRM
freq,NaN,1,33,22493,5034,22564,4772,1072,4532,6,57,1,46007,65,80,50000
mean,125000.500000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
std,14433.901067,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
min,100001.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25%,112500.750000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50%,125000.500000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75%,137500.250000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
max,150000.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
# Save to csv and parquet
customers.to_csv(
    "customer_50000.csv",
    index=False
)

customers.to_parquet(
    "customer_50000.parquet",
    index=False
)

print("Dataset generated successfully.")

Dataset generated successfully.

## Dates

In [ ]:
# Install
!pip install pandas -q

In [ ]:
# Import libraries
import pandas as pd
from google.colab import files

In [ ]:
# Configuration
START_DATE = "2023-01-01"
END_DATE   = "2032-12-31"

In [ ]:
# calendar generator
dates = pd.date_range(
    start=START_DATE,
    end=END_DATE,
    freq="D"
)

calendar = pd.DataFrame()

calendar["DateKey"] = dates.strftime("%Y%m%d").astype(int)

calendar["CalendarDate"] = dates

calendar["Day"] = dates.day

calendar["DayName"] = dates.day_name()

calendar["DayOfWeek"] = dates.dayofweek + 1

calendar["WeekNumber"] = dates.strftime("%V").astype(int)

calendar["MonthNumber"] = dates.month

calendar["MonthName"] = dates.month_name()

calendar["Quarter"] = "Q" + dates.quarter.astype(str)

calendar["CalendarYear"] = dates.year

calendar["IsWeekend"] = (
    dates.dayofweek >= 5
).astype(int)

calendar["IsMonthEnd"] = dates.is_month_end.astype(int)

calendar["IsMonthStart"] = dates.is_month_start.astype(int)

calendar["IsQuarterEnd"] = dates.is_quarter_end.astype(int)

calendar["IsQuarterStart"] = dates.is_quarter_start.astype(int)

calendar["IsYearEnd"] = dates.is_year_end.astype(int)

calendar["IsYearStart"] = dates.is_year_start.astype(int)

calendar["FiscalMonth"] = dates.month

calendar["FiscalQuarter"] = "Q" + dates.quarter.astype(str)

calendar["FiscalYear"] = dates.year

calendar["SourceSystem"] = "Calendar Generator"

calendar.head()

,DateKey,CalendarDate,Day,DayName,DayOfWeek,WeekNumber,MonthNumber,MonthName,Quarter,CalendarYear,...,IsMonthEnd,IsMonthStart,IsQuarterEnd,IsQuarterStart,IsYearEnd,IsYearStart,FiscalMonth,FiscalQuarter,FiscalYear,SourceSystem
0,20230101,2023-01-01,1,Sunday,7,52,1,January,Q1,2023,...,0,1,0,1,0,1,1,Q1,2023,Calendar Generator
1,20230102,2023-01-02,2,Monday,1,1,1,January,Q1,2023,...,0,0,0,0,0,0,1,Q1,2023,Calendar Generator
2,20230103,2023-01-03,3,Tuesday,2,1,1,January,Q1,2023,...,0,0,0,0,0,0,1,Q1,2023,Calendar Generator
3,20230104,2023-01-04,4,Wednesday,3,1,1,January,Q1,2023,...,0,0,0,0,0,0,1,Q1,2023,Calendar Generator
4,20230105,2023-01-05,5,Thursday,4,1,1,January,Q1,2023,...,0,0,0,0,0,0,1,Q1,2023,Calendar Generator

In [ ]:
# Validate
print(calendar.shape)

calendar.info()

calendar.head()

calendar.tail()

(3653, 21)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3653 entries, 0 to 3652
Data columns (total 21 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   DateKey         3653 non-null   int64
 1   CalendarDate    3653 non-null   datetime64[ns]
 2   Day             3653 non-null   int32
 3   DayName         3653 non-null   object
 4   DayOfWeek       3653 non-null   int32
 5   WeekNumber      3653 non-null   int64
 6   MonthNumber     3653 non-null   int32
 7   MonthName       3653 non-null   object
 8   Quarter         3653 non-null   object
 9   CalendarYear    3653 non-null   int32
 10  IsWeekend       3653 non-null   int64
 11  IsMonthEnd      3653 non-null   int64
 12  IsMonthStart    3653 non-null   int64
 13  IsQuarterEnd    3653 non-null   int64
 14  IsQuarterStart  3653 non-null   int64
 15  IsYearEnd       3653 non-null   int64
 16  IsYearStart     3653 non-null   int64
 17  FiscalMonth     3653 non-null   int32
 18  FiscalQuarter   3653 non-null   object
 19  FiscalYear      3653 non-null   int32
 20  SourceSystem    3653 non-null   object
dtypes: datetime64[ns](1), int32(6), int64(9), object(5)
memory usage: 513.8+ KB

,DateKey,CalendarDate,Day,DayName,DayOfWeek,WeekNumber,MonthNumber,MonthName,Quarter,CalendarYear,...,IsMonthEnd,IsMonthStart,IsQuarterEnd,IsQuarterStart,IsYearEnd,IsYearStart,FiscalMonth,FiscalQuarter,FiscalYear,SourceSystem
3648,20321227,2032-12-27,27,Monday,1,53,12,December,Q4,2032,...,0,0,0,0,0,0,12,Q4,2032,Calendar Generator
3649,20321228,2032-12-28,28,Tuesday,2,53,12,December,Q4,2032,...,0,0,0,0,0,0,12,Q4,2032,Calendar Generator
3650,20321229,2032-12-29,29,Wednesday,3,53,12,December,Q4,2032,...,0,0,0,0,0,0,12,Q4,2032,Calendar Generator
3651,20321230,2032-12-30,30,Thursday,4,53,12,December,Q4,2032,...,0,0,0,0,0,0,12,Q4,2032,Calendar Generator
3652,20321231,2032-12-31,31,Friday,5,53,12,December,Q4,2032,...,1,0,1,0,1,0,12,Q4,2032,Calendar Generator

In [ ]:
# csv
calendar.to_csv(
    "calendar_3653.csv",
    index=False
)

print("Calendar generated successfully.")

Calendar generated successfully.

## Products

In [ ]:
import pandas as pd
import numpy as np
from faker import Faker
import random

fake = Faker()

random.seed(42)
np.random.seed(42)

num_products = 5000

categories = [
    "Hardware",
    "Software",
    "Cloud",
    "Networking",
    "Security",
    "Services",
    "Storage",
    "Collaboration"
]

subcategories = {
    "Hardware":["Laptop","Desktop","Server","Monitor"],
    "Software":["Operating System","Database","Analytics","Office"],
    "Cloud":["Compute","Storage","AI","Networking"],
    "Networking":["Router","Switch","Firewall","Wireless"],
    "Security":["Identity","Endpoint","Threat Protection","Encryption"],
    "Services":["Consulting","Support","Training","Implementation"],
    "Storage":["SAN","NAS","Backup","Archive"],
    "Collaboration":["Email","Meetings","Voice","Productivity"]
}

brands = [
    "Microsoft",
    "Dell",
    "HP",
    "Cisco",
    "VMware",
    "Citrix",
    "Lenovo",
    "Adobe"
]

rows = []

for i in range(num_products):

    category = random.choice(categories)
    subcategory = random.choice(subcategories[category])

    rows.append({

        "ProductID":100001+i,
        "ProductCode":f"PROD-{100001+i}",
        "ProductName":fake.catch_phrase(),
        "Category":category,
        "SubCategory":subcategory,
        "Brand":random.choice(brands),
        "UnitPrice":round(random.uniform(50,5000),2),
        "StandardCost":round(random.uniform(25,4000),2),
        "Status":"Active",
        "CreatedDate":fake.date_between(start_date='-5y', end_date='today'),
        "ModifiedDate":fake.date_between(start_date='-2y', end_date='today'),
        "SourceSystem":"ERP"

    })

df = pd.DataFrame(rows)

df.to_csv("product_5000.csv",index=False)

df.head()

,ProductID,ProductCode,ProductName,Category,SubCategory,Brand,UnitPrice,StandardCost,Status,CreatedDate,ModifiedDate,SourceSystem
0,100001,PROD-100001,Virtual 5thgeneration core,Software,Operating System,VMware,1262.21,579.66,Active,2024-10-10,2024-08-23,ERP
1,100002,PROD-100002,Managed secondary portal,Software,Operating System,Lenovo,207.32,397.44,Active,2022-04-04,2025-02-19,ERP
2,100003,PROD-100003,Re-engineered bi-directional knowledgebase,Networking,Router,Cisco,3594.30,2812.77,Active,2022-03-10,2025-08-04,ERP
3,100004,PROD-100004,Realigned explicit software,Storage,NAS,Adobe,2966.87,3242.49,Active,2022-01-12,2025-12-17,ERP
4,100005,PROD-100005,Centralized real-time software,Hardware,Desktop,Lenovo,1734.24,643.03,Active,2023-06-29,2025-07-03,ERP

## Geographies

In [ ]:
# ============================================================
# Enterprise SQL Platform
# Sprint 5 - Geography Dataset Generator
# Dataset : geography_250.csv
# Records : 250
# ============================================================

import pandas as pd
import numpy as np
import random
from datetime import datetime

# ------------------------------------------------------------
# Configuration
# ------------------------------------------------------------

NUM_ROWS = 250
OUTPUT_FILE = "geography_250.csv"

random.seed(42)
np.random.seed(42)

# ------------------------------------------------------------
# Master Geography Data
# ------------------------------------------------------------

locations = [

("India","Karnataka","Bangalore","South",12.9716,77.5946),
("India","Maharashtra","Mumbai","West",19.0760,72.8777),
("India","Delhi","New Delhi","North",28.6139,77.2090),
("India","Tamil Nadu","Chennai","South",13.0827,80.2707),
("India","Telangana","Hyderabad","South",17.3850,78.4867),
("India","Kerala","Kochi","South",9.9312,76.2673),
("India","West Bengal","Kolkata","East",22.5726,88.3639),
("India","Gujarat","Ahmedabad","West",23.0225,72.5714),
("India","Punjab","Ludhiana","North",30.9010,75.8573),
("India","Rajasthan","Jaipur","North",26.9124,75.7873),

("USA","California","San Francisco","West",37.7749,-122.4194),
("USA","Texas","Dallas","Central",32.7767,-96.7970),
("USA","Washington","Seattle","West",47.6062,-122.3321),
("USA","New York","New York","East",40.7128,-74.0060),

("Canada","Ontario","Toronto","East",43.6532,-79.3832),
("Canada","British Columbia","Vancouver","West",49.2827,-123.1207),

("United Kingdom","England","London","EMEA",51.5074,-0.1278),
("Germany","Bavaria","Munich","EMEA",48.1351,11.5820),
("France","Ile-de-France","Paris","EMEA",48.8566,2.3522),
("Netherlands","North Holland","Amsterdam","EMEA",52.3676,4.9041),

("UAE","Dubai","Dubai","Middle East",25.2048,55.2708),
("Saudi Arabia","Riyadh","Riyadh","Middle East",24.7136,46.6753),

("Singapore","Singapore","Singapore","APAC",1.3521,103.8198),
("Australia","New South Wales","Sydney","ANZ",-33.8688,151.2093),
("Japan","Tokyo","Tokyo","APAC",35.6762,139.6503)

]

# ------------------------------------------------------------
# Generate Dataset
# ------------------------------------------------------------

rows = []

today = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

for i in range(1, NUM_ROWS + 1):

    location = random.choice(locations)

    geography_id = 1000 + i

    rows.append({

        "GeographyID": geography_id,
        "GeographyCode": f"GEO-{geography_id}",
        "Country": location[0],
        "StateProvince": location[1],
        "City": location[2],
        "Region": location[3],
        "PostalCode": random.randint(100000,999999),
        "Latitude": round(location[4] + random.uniform(-0.08,0.08),6),
        "Longitude": round(location[5] + random.uniform(-0.08,0.08),6),
        "SourceSystem": "Google Colab",
        "CreatedDate": today,
        "ModifiedDate": today

    })

df = pd.DataFrame(rows)

# ------------------------------------------------------------
# Save CSV
# ------------------------------------------------------------

df.to_csv(OUTPUT_FILE, index=False)

print("=" * 60)
print("Enterprise SQL Platform")
print("Geography Dataset Generator")
print("=" * 60)
print(f"Rows Generated : {len(df):,}")
print(f"Output File    : {OUTPUT_FILE}")
print("=" * 60)

display(df.head(10))

# ------------------------------------------------------------
# Download CSV
# ------------------------------------------------------------

from google.colab import files
files.download(OUTPUT_FILE)

============================================================
Enterprise SQL Platform
Geography Dataset Generator
============================================================
Rows Generated : 250
Output File    : geography_250.csv
============================================================

,GeographyID,GeographyCode,Country,StateProvince,City,Region,PostalCode,Latitude,Longitude,SourceSystem,CreatedDate,ModifiedDate
0,1001,GEO-1001,UAE,Dubai,Dubai,Middle East,216739,25.128802,55.234805,Google Colab,2026-08-06 10:53:58,2026-08-06 10:53:58
1,1002,GEO-1002,India,Gujarat,Ahmedabad,West,246316,23.060335,72.599672,Google Colab,2026-08-06 10:53:58,2026-08-06 10:53:58
2,1003,GEO-1003,Germany,Bavaria,Munich,EMEA,191161,48.149579,11.507085,Google Colab,2026-08-06 10:53:58,2026-08-06 10:53:58
3,1004,GEO-1004,India,Delhi,New Delhi,North,329258,28.571126,77.225323,Google Colab,2026-08-06 10:53:58,2026-08-06 10:53:58
4,1005,GEO-1005,Germany,Bavaria,Munich,EMEA,308496,48.169663,11.614212,Google Colab,2026-08-06 10:53:58,2026-08-06 10:53:58
5,1006,GEO-1006,USA,New York,New York,East,331148,40.704673,-74.041489,Google Colab,2026-08-06 10:53:58,2026-08-06 10:53:58
6,1007,GEO-1007,India,Karnataka,Bangalore,South,895667,13.020531,77.626302,Google Colab,2026-08-06 10:53:58,2026-08-06 10:53:58
7,1008,GEO-1008,USA,California,San Francisco,West,391369,37.719777,-122.346246,Google Colab,2026-08-06 10:53:58,2026-08-06 10:53:58
8,1009,GEO-1009,USA,California,San Francisco,West,207175,37.709739,-122.483925,Google Colab,2026-08-06 10:53:58,2026-08-06 10:53:58
9,1010,GEO-1010,USA,Texas,Dallas,Central,733052,32.739023,-96.870048,Google Colab,2026-08-06 10:53:58,2026-08-06 10:53:58

## Sales Territories

In [ ]:
# ============================================================
# Enterprise SQL Platform
# Sprint 5 - Sales Territory Dataset Generator
# Dataset : salesterritory_50.csv
# Records : 50
# ============================================================

import pandas as pd
import numpy as np
import random
from datetime import datetime

# ------------------------------------------------------------
# Configuration
# ------------------------------------------------------------

NUM_ROWS = 50
OUTPUT_FILE = "salesterritory_50.csv"

random.seed(42)
np.random.seed(42)

# ------------------------------------------------------------
# Master Data
# ------------------------------------------------------------

territories = [
    ("India North","North","India"),
    ("India South","South","India"),
    ("India East","East","India"),
    ("India West","West","India"),
    ("India Central","Central","India"),

    ("USA East","East","USA"),
    ("USA West","West","USA"),
    ("USA Central","Central","USA"),

    ("Canada East","East","Canada"),
    ("Canada West","West","Canada"),

    ("UK","EMEA","United Kingdom"),
    ("Germany","EMEA","Germany"),
    ("France","EMEA","France"),
    ("Netherlands","EMEA","Netherlands"),

    ("Middle East North","Middle East","UAE"),
    ("Middle East South","Middle East","Saudi Arabia"),

    ("Singapore","APAC","Singapore"),
    ("Japan","APAC","Japan"),
    ("Australia","ANZ","Australia")
]

first_names = [
    "Rajesh","Amit","Vikram","Rahul","Anil",
    "Sarah","John","Michael","Emma","David",
    "Priya","Neha","Karan","Sanjay","Arun",
    "James","William","Sophia","Olivia","Daniel"
]

last_names = [
    "Sharma","Patel","Nair","Menon","Reddy",
    "Smith","Johnson","Brown","Taylor","Wilson",
    "Gupta","Verma","Kapoor","Thomas","Joseph"
]

# ------------------------------------------------------------
# Generate Dataset
# ------------------------------------------------------------

rows = []

today = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

for i in range(1, NUM_ROWS + 1):

    territory = random.choice(territories)

    territory_id = 100 + i

    manager = f"{random.choice(first_names)} {random.choice(last_names)}"

    rows.append({

        "TerritoryID": territory_id,
        "TerritoryCode": f"ST-{territory_id}",
        "TerritoryName": territory[0],
        "Region": territory[1],
        "Country": territory[2],
        "TerritoryManager": manager,
        "Status": random.choices(
            ["Active", "Inactive"],
            weights=[95, 5]
        )[0],
        "SourceSystem": "Google Colab",
        "CreatedDate": today,
        "ModifiedDate": today

    })

df = pd.DataFrame(rows)

# ------------------------------------------------------------
# Save CSV
# ------------------------------------------------------------

df.to_csv(OUTPUT_FILE, index=False)

print("=" * 60)
print("Enterprise SQL Platform")
print("Sales Territory Dataset Generator")
print("=" * 60)
print(f"Rows Generated : {len(df):,}")
print(f"Output File    : {OUTPUT_FILE}")
print("=" * 60)

display(df.head(10))

# ------------------------------------------------------------
# Download CSV
# ------------------------------------------------------------

from google.colab import files
files.download(OUTPUT_FILE)

============================================================
Enterprise SQL Platform
Sales Territory Dataset Generator
============================================================
Rows Generated : 50
Output File    : salesterritory_50.csv
============================================================

,TerritoryID,TerritoryCode,TerritoryName,Region,Country,TerritoryManager,Status,SourceSystem,CreatedDate,ModifiedDate
0,101,ST-101,India West,West,India,Rajesh Verma,Active,Google Colab,2026-08-06 10:53:58,2026-08-06 10:53:58
1,102,ST-102,USA Central,Central,USA,Anil Verma,Active,Google Colab,2026-08-06 10:53:58,2026-08-06 10:53:58
2,103,ST-103,Japan,APAC,Japan,Vikram Wilson,Active,Google Colab,2026-08-06 10:53:58,2026-08-06 10:53:58
3,104,ST-104,India North,North,India,Vikram Menon,Active,Google Colab,2026-08-06 10:53:58,2026-08-06 10:53:58
4,105,ST-105,India North,North,India,Sophia Menon,Active,Google Colab,2026-08-06 10:53:58,2026-08-06 10:53:58
5,106,ST-106,Japan,APAC,Japan,Sanjay Menon,Active,Google Colab,2026-08-06 10:53:58,2026-08-06 10:53:58
6,107,ST-107,Canada East,East,Canada,Rajesh Kapoor,Active,Google Colab,2026-08-06 10:53:58,2026-08-06 10:53:58
7,108,ST-108,Netherlands,EMEA,Netherlands,Priya Reddy,Active,Google Colab,2026-08-06 10:53:58,2026-08-06 10:53:58
8,109,ST-109,UK,EMEA,United Kingdom,Rahul Patel,Active,Google Colab,2026-08-06 10:53:58,2026-08-06 10:53:58
9,110,ST-110,Germany,EMEA,Germany,Neha Wilson,Active,Google Colab,2026-08-06 10:53:58,2026-08-06 10:53:58

## Salespersons

In [ ]:
# ============================================================
# Enterprise SQL Platform
# Sprint 5 - Salesperson Dataset Generator
# Dataset : salesperson_500.csv
# Records : 500
# ============================================================

import pandas as pd
import numpy as np
import random
from datetime import datetime, timedelta

# ------------------------------------------------------------
# Configuration
# ------------------------------------------------------------

NUM_ROWS = 500
OUTPUT_FILE = "salesperson_500.csv"

random.seed(42)
np.random.seed(42)

# ------------------------------------------------------------
# Master Data
# ------------------------------------------------------------

first_names = [

"Rajesh","Amit","Rahul","Vikram","Anil",
"Priya","Neha","Sneha","Pooja","Asha",
"John","David","Michael","James","Daniel",
"Sarah","Emma","Sophia","Olivia","Emily",
"Arun","Sanjay","Karan","Rohit","Ajay",
"Kevin","Brian","Jason","William","Andrew"

]

last_names = [

"Sharma","Patel","Nair","Menon","Reddy",
"Gupta","Kapoor","Thomas","Joseph","Verma",
"Smith","Johnson","Brown","Taylor","Wilson",
"Anderson","Martin","Clark","Lewis","Walker"

]

job_titles = [

"Account Executive",
"Senior Account Executive",
"Account Manager",
"Senior Account Manager",
"Sales Executive",
"Sales Consultant",
"Territory Manager",
"Regional Sales Manager",
"Business Development Manager",
"Enterprise Account Manager"

]

domains = [
"enterprise.com",
"contoso.com",
"adventureworks.com"
]

# ------------------------------------------------------------
# Generate Dataset
# ------------------------------------------------------------

rows = []

today = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

for i in range(1, NUM_ROWS + 1):

    salesperson_id = 10000 + i

    first = random.choice(first_names)
    last = random.choice(last_names)

    email = (
        first.lower() + "." +
        last.lower() +
        str(random.randint(1,999)) +
        "@" +
        random.choice(domains)
    )

    hire_date = (
        datetime(2017,1,1) +
        timedelta(days=random.randint(0,3000))
    ).strftime("%Y-%m-%d")

    rows.append({

        "SalespersonID": salesperson_id,
        "EmployeeCode": f"EMP{salesperson_id}",
        "FirstName": first,
        "LastName": last,
        "FullName": first + " " + last,
        "Email": email,
        "TerritoryID": random.randint(101,150),
        "JobTitle": random.choice(job_titles),
        "HireDate": hire_date,
        "Status": random.choices(
            ["Active","Inactive"],
            weights=[90,10]
        )[0],
        "SourceSystem": "Google Colab",
        "CreatedDate": today,
        "ModifiedDate": today

    })

df = pd.DataFrame(rows)

# ------------------------------------------------------------
# Save CSV
# ------------------------------------------------------------

df.to_csv(OUTPUT_FILE, index=False)

print("=" * 60)
print("Enterprise SQL Platform")
print("Salesperson Dataset Generator")
print("=" * 60)
print(f"Rows Generated : {len(df):,}")
print(f"Output File    : {OUTPUT_FILE}")
print("=" * 60)

display(df.head(10))

# ------------------------------------------------------------
# Download CSV
# ------------------------------------------------------------

from google.colab import files
files.download(OUTPUT_FILE)

============================================================
Enterprise SQL Platform
Salesperson Dataset Generator
============================================================
Rows Generated : 500
Output File    : salesperson_500.csv
============================================================

,SalespersonID,EmployeeCode,FirstName,LastName,FullName,Email,TerritoryID,JobTitle,HireDate,Status,SourceSystem,CreatedDate,ModifiedDate
0,10001,EMP10001,Arun,Menon,Arun Menon,arun.menon26@adventureworks.com,116,Senior Account Manager,2020-02-01,Active,Google Colab,2026-08-06 10:53:58,2026-08-06 10:53:58
1,10002,EMP10002,Vikram,Clark,Vikram Clark,vikram.clark90@adventureworks.com,103,Account Executive,2021-09-25,Active,Google Colab,2026-08-06 10:53:58,2026-08-06 10:53:58
2,10003,EMP10003,Sneha,Martin,Sneha Martin,sneha.martin617@enterprise.com,113,Business Development Manager,2023-04-18,Active,Google Colab,2026-08-06 10:53:58,2026-08-06 10:53:58
3,10004,EMP10004,Daniel,Lewis,Daniel Lewis,daniel.lewis285@enterprise.com,145,Territory Manager,2018-10-16,Active,Google Colab,2026-08-06 10:53:58,2026-08-06 10:53:58
4,10005,EMP10005,Anil,Kapoor,Anil Kapoor,anil.kapoor981@contoso.com,106,Territory Manager,2018-02-23,Active,Google Colab,2026-08-06 10:53:58,2026-08-06 10:53:58
5,10006,EMP10006,Jason,Johnson,Jason Johnson,jason.johnson619@contoso.com,147,Regional Sales Manager,2017-06-27,Active,Google Colab,2026-08-06 10:53:58,2026-08-06 10:53:58
6,10007,EMP10007,Andrew,Brown,Andrew Brown,andrew.brown81@adventureworks.com,141,Enterprise Account Manager,2020-04-15,Active,Google Colab,2026-08-06 10:53:58,2026-08-06 10:53:58
7,10008,EMP10008,David,Lewis,David Lewis,david.lewis197@adventureworks.com,103,Senior Account Manager,2017-10-12,Active,Google Colab,2026-08-06 10:53:58,2026-08-06 10:53:58
8,10009,EMP10009,Rahul,Thomas,Rahul Thomas,rahul.thomas888@enterprise.com,118,Regional Sales Manager,2021-04-06,Active,Google Colab,2026-08-06 10:53:58,2026-08-06 10:53:58
9,10010,EMP10010,David,Gupta,David Gupta,david.gupta380@contoso.com,143,Sales Executive,2019-05-09,Active,Google Colab,2026-08-06 10:53:58,2026-08-06 10:53:58

# Facts

In [ ]:
# ============================================
# Business Simulation Configuration
# ============================================

NUM_INVOICES = 200000
TARGET_INVOICE_LINES = 500000

RANDOM_SEED = 42

START_YEAR = 2016
END_YEAR = 2025

In [ ]:
customer_segment_distribution = {
    "Enterprise": 0.05,
    "MidMarket": 0.20,
    "SMB": 0.75
}

In [ ]:
quarter_distribution = {
    1: 0.22,
    2: 0.23,
    3: 0.24,
    4: 0.31
}

In [ ]:
sales_channel_distribution = {
    "Direct": 0.50,
    "Partner": 0.30,
    "Distributor": 0.15,
    "Online": 0.05
}

In [ ]:
order_status_distribution = {
    "Completed": 0.95,
    "Pending": 0.03,
    "Cancelled": 0.02
}

In [ ]:
# Function 1: Initialize random seed

import random
import numpy as np

random.seed(RANDOM_SEED)
np.random.seed(RANDOM_SEED)

In [ ]:
# Function 2: Select invoice Date

def select_invoice_date():
    row = calendar_df.sample(n=1).iloc[0]

    return {
        "DateKey": int(row["DateKey"]),
        "InvoiceDate": row["Date"]
    }

In [ ]:
# Function 3: Select Customer

def select_customer():
    row = customer_df.sample(n=1).iloc[0]

    return {
        "CustomerID": int(row["CustomerID"]),
        "CustomerName": row["CustomerName"]
    }

In [ ]:
# Function 4 - Select Product

def select_product():
    row = product_df.sample(n=1).iloc[0]

    return {
        "ProductID": int(row["ProductID"]),
        "ProductName": row["ProductName"]
    }

In [ ]:
# Function 5 - Select Geography

def select_geography():
    row = geography_df.sample(n=1).iloc[0]

    return {
        "GeographyID": int(row["GeographyID"]),
        "Country": row["Country"],
        "Region": row["Region"]
    }

In [ ]:
# Function 6 Select Sales Territory

def select_sales_territory():
    row = territory_df.sample(n=1).iloc[0]

    return {
        "TerritoryID": int(row["TerritoryID"]),
        "TerritoryName": row["TerritoryName"]
    }

In [ ]:
# Function 7: Select Salesperson

def select_salesperson():
    row = salesperson_df.sample(n=1).iloc[0]

    return {
        "SalespersonID": int(row["SalespersonID"]),
        "Salesperson": row["FullName"]
    }

In [ ]:
# Function 8: Calculate Quantity

def calculate_quantity():

    return random.choices(
        population=[1,2,3,4,5,10,15,20],
        weights=[35,25,15,10,5,5,3,2],
        k=1
    )[0]

In [ ]:
# Function 9:  Calculcate Unit Price

def calculate_unit_price(base_price):

    variation = random.uniform(0.90,1.10)

    return round(base_price * variation,2)

In [ ]:
# Function 10 - Calculate Discount

def calculate_discount():

    return random.choices(
        population=[0,5,10,15,20],
        weights=[60,20,12,6,2],
        k=1
    )[0]

In [ ]:
# Function 11 - Calculate Financials

def calculate_financials(
        quantity,
        unit_price,
        discount_percent,
        cost_percent):

    gross_sales = quantity * unit_price

    discount_amount = gross_sales * discount_percent / 100

    net_sales = gross_sales - discount_amount

    cost = net_sales * cost_percent

    gross_margin = net_sales - cost

    gross_margin_percent = (
        gross_margin / net_sales * 100
        if net_sales > 0 else 0
    )

    return {
        "GrossSalesAmount": round(gross_sales,2),
        "DiscountAmount": round(discount_amount,2),
        "NetSalesAmount": round(net_sales,2),
        "CostAmount": round(cost,2),
        "GrossMarginAmount": round(gross_margin,2),
        "GrossMarginPercent": round(gross_margin_percent,2)
    }

In [ ]:
# Function 12: Sales Channel

def select_sales_channel():

    return random.choices(
        population=[
            "Direct",
            "Partner",
            "Distributor",
            "Online"
        ],
        weights=[
            50,
            30,
            15,
            5
        ],
        k=1
    )[0]

In [ ]:
# Function 13 - Order Status

def select_order_status():

    return random.choices(
        population=[
            "Completed",
            "Pending",
            "Cancelled"
        ],
        weights=[
            95,
            3,
            2
        ],
        k=1
    )[0]

In [ ]:
# Set dataframes

customer_df = pd.read_csv("customer_50000.csv")

calendar_df = pd.read_csv("calendar_3653.csv")

product_df = pd.read_csv("product_5000.csv")

geography_df = pd.read_csv("geography_250.csv")

territory_df = pd.read_csv("salesterritory_50.csv")

salesperson_df = pd.read_csv("salesperson_500.csv")

In [ ]:
for name, df in [
    ("customer", customer_df),
    ("calendar", calendar_df),
    ("product", product_df),
    ("geography", geography_df),
    ("territory", territory_df),
    ("salesperson", salesperson_df),
]:
    print(f"\n{name.upper()}")
    print(df.columns.tolist())

CUSTOMER
['CustomerID', 'CustomerCode', 'CustomerName', 'CustomerType', 'Industry', 'SalesTerritory', 'Country', 'StateProvince', 'City', 'PostalCode', 'EmailAddress', 'PhoneNumber', 'Status', 'CreatedDate', 'ModifiedDate', 'SourceSystem']

CALENDAR
['DateKey', 'CalendarDate', 'Day', 'DayName', 'DayOfWeek', 'WeekNumber', 'MonthNumber', 'MonthName', 'Quarter', 'CalendarYear', 'IsWeekend', 'IsMonthEnd', 'IsMonthStart', 'IsQuarterEnd', 'IsQuarterStart', 'IsYearEnd', 'IsYearStart', 'FiscalMonth', 'FiscalQuarter', 'FiscalYear', 'SourceSystem']

PRODUCT
['ProductID', 'ProductCode', 'ProductName', 'Category', 'SubCategory', 'Brand', 'UnitPrice', 'StandardCost', 'Status', 'CreatedDate', 'ModifiedDate', 'SourceSystem']

GEOGRAPHY
['GeographyID', 'GeographyCode', 'Country', 'StateProvince', 'City', 'Region', 'PostalCode', 'Latitude', 'Longitude', 'SourceSystem', 'CreatedDate', 'ModifiedDate']

TERRITORY
['TerritoryID', 'TerritoryCode', 'TerritoryName', 'Region', 'Country', 'TerritoryManager', 'Status', 'SourceSystem', 'CreatedDate', 'ModifiedDate']

SALESPERSON
['SalespersonID', 'EmployeeCode', 'FirstName', 'LastName', 'FullName', 'Email', 'TerritoryID', 'JobTitle', 'HireDate', 'Status', 'SourceSystem', 'CreatedDate', 'ModifiedDate']

In [ ]:
print(len(customer_df))
print(len(calendar_df))
print(len(product_df))
print(len(geography_df))
print(len(territory_df))
print(len(salesperson_df))

50000
3653
5000
250
50
500

### Block A
Configuration, master data loading, helper functions.

In [ ]:
# ============================================================
# Enterprise SQL Platform Lab
# Business Simulation Engine v1.0
#
# BLOCK A1
# Configuration
# Load Master Data
# Selection Functions
# ============================================================

import pandas as pd
import numpy as np
import random

# ------------------------------------------------------------
# Configuration
# ------------------------------------------------------------

NUMBER_OF_INVOICES = 200000
TARGET_INVOICE_LINES = 500000
RANDOM_SEED = 42

random.seed(RANDOM_SEED)
np.random.seed(RANDOM_SEED)

# ------------------------------------------------------------
# Load Master Data
# ------------------------------------------------------------

customer_df = pd.read_csv("customer_50000.csv")
calendar_df = pd.read_csv("calendar_3653.csv")
product_df = pd.read_csv("product_5000.csv")
geography_df = pd.read_csv("geography_250.csv")
territory_df = pd.read_csv("salesterritory_50.csv")
salesperson_df = pd.read_csv("salesperson_500.csv")

print("==========================================")
print("MASTER DATA LOADED")
print("==========================================")

print(f"Customers      : {len(customer_df):,}")
print(f"Calendar       : {len(calendar_df):,}")
print(f"Products       : {len(product_df):,}")
print(f"Geographies    : {len(geography_df):,}")
print(f"Territories    : {len(territory_df):,}")
print(f"Salespersons   : {len(salesperson_df):,}")

# ------------------------------------------------------------
# Selection Functions
# ------------------------------------------------------------

def select_calendar():
    return calendar_df.sample(1).iloc[0]


def select_customer():
    return customer_df.sample(1).iloc[0]


def select_product():
    return product_df.sample(1).iloc[0]


def select_geography():
    return geography_df.sample(1).iloc[0]


def select_salesperson():
    return salesperson_df.sample(1).iloc[0]


def select_territory(territory_id):

    match = territory_df[
        territory_df["TerritoryID"] == territory_id
    ]

    if len(match) == 0:
        return territory_df.sample(1).iloc[0]

    return match.iloc[0]

print("\nSelection Functions Loaded.")

==========================================
MASTER DATA LOADED
==========================================
Customers      : 50,000
Calendar       : 3,653
Products       : 5,000
Geographies    : 250
Territories    : 50
Salespersons   : 500

Selection Functions Loaded.

In [ ]:
# ============================================================
# BLOCK A2
# Business Rules
# Financial Engine
# ============================================================

# ------------------------------------------------------------
# Quantity Distribution
# ------------------------------------------------------------

def calculate_quantity():

    return random.choices(

        population=[1,2,3,4,5,6,8,10,15,20],

        weights=[25,20,15,12,10,6,5,4,2,1],

        k=1

    )[0]


# ------------------------------------------------------------
# Unit Price
# ------------------------------------------------------------

def calculate_unit_price(base_price):

    multiplier = random.uniform(0.98,1.02)

    return round(base_price * multiplier,2)


# ------------------------------------------------------------
# Discount
# ------------------------------------------------------------

def calculate_discount_percent():

    return random.choices(

        population=[0,5,10,15,20],

        weights=[60,20,12,6,2],

        k=1

    )[0]


# ------------------------------------------------------------
# Sales Channel
# ------------------------------------------------------------

def select_sales_channel():

    return random.choices(

        population=[
            "Direct",
            "Partner",
            "Distributor",
            "Online"
        ],

        weights=[
            50,
            30,
            15,
            5
        ],

        k=1

    )[0]


# ------------------------------------------------------------
# Order Status
# ------------------------------------------------------------

def select_order_status():

    return random.choices(

        population=[
            "Completed",
            "Pending",
            "Cancelled"
        ],

        weights=[
            95,
            3,
            2
        ],

        k=1

    )[0]


# ------------------------------------------------------------
# Financial Engine
# ------------------------------------------------------------

def calculate_financials(

    quantity,
    unit_price,
    standard_cost,
    discount_percent

):

    gross_sales = quantity * unit_price

    discount_amount = round(
        gross_sales * discount_percent / 100,
        2
    )

    net_sales = round(
        gross_sales - discount_amount,
        2
    )

    cost_amount = round(
        quantity * standard_cost,
        2
    )

    # Prevent unrealistic loss-making transactions

    if cost_amount >= net_sales:

        target_margin = random.uniform(0.18,0.42)

        cost_amount = round(
            net_sales * (1-target_margin),
            2
        )

    gross_margin = round(
        net_sales - cost_amount,
        2
    )

    gross_margin_percent = round(

        (gross_margin / net_sales) * 100,

        2

    )

    return (

        gross_sales,
        discount_amount,
        net_sales,
        cost_amount,
        gross_margin,
        gross_margin_percent

    )


# ------------------------------------------------------------
# Invoice Numbers
# ------------------------------------------------------------

def generate_invoice_number(invoice):

    return f"INV-{invoice:08d}"


def generate_sales_order_number(invoice):

    return f"SO-{invoice:08d}"


# ------------------------------------------------------------
# Invoice Line Distribution
# ------------------------------------------------------------

def generate_line_count():

    return random.choices(

        population=[1,2,3,4,5],

        # Average ≈ 2.55 lines/invoice

        weights=[25,30,20,15,10],

        k=1

    )[0]


print("\nBusiness Rules Loaded Successfully.")

Business Rules Loaded Successfully.

### BLOCK B - Generate Invoice Headers & Expand to Invoice Lines

In [ ]:
# ============================================================
# BLOCK B
# Generate Invoice Headers
# Generate Invoice Lines
# ============================================================

sales_rows = []

invoice_line_counter = 0

print("Generating Sales Transactions...\n")

for invoice_id in range(1, NUMBER_OF_INVOICES + 1):

    cal = select_calendar()

    customer = select_customer()

    geography = select_geography()

    salesperson = select_salesperson()

    territory = select_territory(
        salesperson["TerritoryID"]
    )

    line_count = generate_line_count()

    for line in range(1, line_count + 1):

        if invoice_line_counter >= TARGET_INVOICE_LINES:
            break

        product = select_product()

        quantity = calculate_quantity()

        unit_price = calculate_unit_price(
            product["UnitPrice"]
        )

        discount_percent = calculate_discount_percent()

        (
            gross_sales,
            discount_amount,
            net_sales,
            cost_amount,
            gross_margin,
            gross_margin_percent

        ) = calculate_financials(

            quantity,
            unit_price,
            product["StandardCost"],
            discount_percent

        )

        sales_rows.append({

            "SalesID":
                invoice_id,

            "SalesOrderNumber":
                generate_sales_order_number(invoice_id),

            "SalesOrderLineNumber":
                line,

            "InvoiceNumber":
                generate_invoice_number(invoice_id),

            "DateKey":
                int(cal["DateKey"]),

            "CustomerID":
                int(customer["CustomerID"]),

            "ProductID":
                int(product["ProductID"]),

            "GeographyID":
                int(geography["GeographyID"]),

            "TerritoryID":
                int(territory["TerritoryID"]),

            "SalespersonID":
                int(salesperson["SalespersonID"]),

            "Quantity":
                quantity,

            "UnitPrice":
                unit_price,

            "GrossSalesAmount":
                gross_sales,

            "DiscountPercent":
                discount_percent,

            "DiscountAmount":
                discount_amount,

            "NetSalesAmount":
                net_sales,

            "CostAmount":
                cost_amount,

            "GrossMarginAmount":
                gross_margin,

            "GrossMarginPercent":
                gross_margin_percent,

            "SalesChannel":
                select_sales_channel(),

            "OrderStatus":
                select_order_status(),

            "CurrencyCode":
                "INR",

            "SourceSystem":
                "ERP",

            "CreatedDate":
                cal["CalendarDate"],

            "ModifiedDate":
                cal["CalendarDate"]

        })

        invoice_line_counter += 1

    if invoice_line_counter >= TARGET_INVOICE_LINES:
        break

    if invoice_id % 10000 == 0:

        print(
            f"Invoices : {invoice_id:,}   "
            f"Invoice Lines : {invoice_line_counter:,}"
        )

print("\nGeneration Complete\n")

print(f"Invoices Created      : {invoice_id:,}")
print(f"Invoice Lines Created : {invoice_line_counter:,}")

sales_df = pd.DataFrame(sales_rows)

print("\nDataFrame Created Successfully")

print(sales_df.head())

print()

print(sales_df.shape)

Generating Sales Transactions...

Invoices : 10,000   Invoice Lines : 25,432
Invoices : 20,000   Invoice Lines : 50,956
Invoices : 30,000   Invoice Lines : 76,364
Invoices : 40,000   Invoice Lines : 101,847
Invoices : 50,000   Invoice Lines : 127,374
Invoices : 60,000   Invoice Lines : 153,102
Invoices : 70,000   Invoice Lines : 178,547
Invoices : 80,000   Invoice Lines : 203,838
Invoices : 90,000   Invoice Lines : 228,992
Invoices : 100,000   Invoice Lines : 254,458
Invoices : 110,000   Invoice Lines : 280,102
Invoices : 120,000   Invoice Lines : 305,410
Invoices : 130,000   Invoice Lines : 330,807
Invoices : 140,000   Invoice Lines : 356,349
Invoices : 150,000   Invoice Lines : 381,959
Invoices : 160,000   Invoice Lines : 407,406
Invoices : 170,000   Invoice Lines : 432,824
Invoices : 180,000   Invoice Lines : 458,349
Invoices : 190,000   Invoice Lines : 483,960

Generation Complete

Invoices Created      : 196,254
Invoice Lines Created : 500,000

DataFrame Created Successfully
   SalesID SalesOrderNumber  SalesOrderLineNumber InvoiceNumber   DateKey  \
0        1      SO-00000001                     1  INV-00000001  20260806
1        1      SO-00000001                     2  INV-00000001  20260806
2        1      SO-00000001                     3  INV-00000001  20260806
3        2      SO-00000002                     1  INV-00000002  20281114
4        2      SO-00000002                     2  INV-00000002  20281114

   CustomerID  ProductID  GeographyID  TerritoryID  SalespersonID  ...  \
0      116811     102569         1077          110          10386  ...
1      116811     103059         1077          110          10386  ...
2      116811     104021         1077          110          10386  ...
3      120353     100121         1086          139          10188  ...
4      120353     103811         1086          139          10188  ...

   NetSalesAmount  CostAmount  GrossMarginAmount  GrossMarginPercent  \
0         3473.93     2431.89            1042.04               30.00
1        26827.68    21173.84            5653.84               21.07
2         2772.18     1840.80             931.38               33.60
3         2089.93     1363.57             726.36               34.76
4        46061.90    23119.90           22942.00               49.81

   SalesChannel  OrderStatus  CurrencyCode  SourceSystem  CreatedDate  \
0       Partner    Completed           INR           ERP   2026-08-06
1        Direct    Completed           INR           ERP   2026-08-06
2       Partner    Completed           INR           ERP   2026-08-06
3        Direct    Completed           INR           ERP   2028-11-14
4        Direct    Completed           INR           ERP   2028-11-14

  ModifiedDate
0   2026-08-06
1   2026-08-06
2   2026-08-06
3   2028-11-14
4   2028-11-14

[5 rows x 25 columns]

(500000, 25)

In [ ]:
# ============================================================
# ENTERPRISE QA VALIDATION
# ============================================================

print("="*60)
print("ENTERPRISE QA VALIDATION")
print("="*60)

print("\nROW COUNTS")
print("------------------------")
print(f"Invoice Lines        : {len(sales_df):,}")
print(f"Invoices             : {sales_df['SalesID'].nunique():,}")
print(f"Customers            : {sales_df['CustomerID'].nunique():,}")
print(f"Products             : {sales_df['ProductID'].nunique():,}")
print(f"Geographies          : {sales_df['GeographyID'].nunique():,}")
print(f"Territories          : {sales_df['TerritoryID'].nunique():,}")
print(f"Salespersons         : {sales_df['SalespersonID'].nunique():,}")

print("\nNULL VALUES")
print("------------------------")
print(sales_df.isnull().sum())

print("\nDUPLICATE CHECK")
print("------------------------")

duplicates = sales_df.duplicated(
    subset=[
        "SalesID",
        "SalesOrderLineNumber"
    ]
).sum()

print(f"Duplicate Invoice Lines : {duplicates:,}")

print("\nFINANCIAL SUMMARY")
print("------------------------")

print(f"Gross Sales      : {sales_df['GrossSalesAmount'].sum():,.2f}")
print(f"Net Sales        : {sales_df['NetSalesAmount'].sum():,.2f}")
print(f"Gross Margin     : {sales_df['GrossMarginAmount'].sum():,.2f}")

print(f"\nAverage Unit Price : {sales_df['UnitPrice'].mean():,.2f}")
print(f"Average Quantity   : {sales_df['Quantity'].mean():,.2f}")
print(f"Average Discount % : {sales_df['DiscountPercent'].mean():,.2f}")
print(f"Average Margin %   : {sales_df['GrossMarginPercent'].mean():,.2f}")

print("\nNEGATIVE MARGIN CHECK")
print("------------------------")

negative = (
    sales_df["GrossMarginAmount"] < 0
).sum()

print(f"Negative Margin Rows : {negative:,}")

print("\nTOP SALES CHANNELS")
print("------------------------")
print(sales_df["SalesChannel"].value_counts())

print("\nORDER STATUS")
print("------------------------")
print(sales_df["OrderStatus"].value_counts())

print("\nQA COMPLETE")

============================================================
ENTERPRISE QA VALIDATION
============================================================

ROW COUNTS
------------------------
Invoice Lines        : 500,000
Invoices             : 196,254
Customers            : 49,058
Products             : 5,000
Geographies          : 250
Territories          : 50
Salespersons         : 500

NULL VALUES
------------------------
SalesID                 0
SalesOrderNumber        0
SalesOrderLineNumber    0
InvoiceNumber           0
DateKey                 0
CustomerID              0
ProductID               0
GeographyID             0
TerritoryID             0
SalespersonID           0
Quantity                0
UnitPrice               0
GrossSalesAmount        0
DiscountPercent         0
DiscountAmount          0
NetSalesAmount          0
CostAmount              0
GrossMarginAmount       0
GrossMarginPercent      0
SalesChannel            0
OrderStatus             0
CurrencyCode            0
SourceSystem            0
CreatedDate             0
ModifiedDate            0
dtype: int64

DUPLICATE CHECK
------------------------
Duplicate Invoice Lines : 0

FINANCIAL SUMMARY
------------------------
Gross Sales      : 4,683,204,031.01
Net Sales        : 4,519,200,133.88
Gross Margin     : 2,079,794,675.62

Average Unit Price : 2,501.85
Average Quantity   : 3.74
Average Discount % : 3.51
Average Margin %   : 41.90

NEGATIVE MARGIN CHECK
------------------------
Negative Margin Rows : 0

TOP SALES CHANNELS
------------------------
SalesChannel
Direct         249982
Partner        150104
Distributor     74817
Online          25097
Name: count, dtype: int64

ORDER STATUS
------------------------
OrderStatus
Completed    474962
Pending       15070
Cancelled      9968
Name: count, dtype: int64

QA COMPLETE

In [ ]:
# Export to CSV

sales_df.to_csv(
    "sales_500000.csv",
    index=False
)

from google.colab import files

files.download("sales_500000.csv")

In [ ]:
# Export to Parquet

sales_df.to_parquet(
    "sales_500000.parquet",
    index=False
)

from google.colab import files

files.download("sales_500000.parquet")